<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="3" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-13T12:19:49 IST" name="Suite" finished-at="2024-11-13T12:20:14 IST" duration-ms="24713">
    <groups>
    </groups>
    <test started-at="2024-11-13T12:19:49 IST" name="Test" finished-at="2024-11-13T12:20:14 IST" duration-ms="24713">
      <class name="comTest.Login">
        <test-method is-config="true" signature="tearUp()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:49 IST" name="tearUp" finished-at="2024-11-13T12:19:54 IST" duration-ms="4313" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method signature="loginWithInvalidCredentials()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:54 IST" name="loginWithInvalidCredentials" finished-at="2024-11-13T12:19:54 IST" duration-ms="659" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at comTest.Login.loginWithInvalidCredentials(Login.java:61)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:55 IST" name="tearDown" finished-at="2024-11-13T12:19:55 IST" duration-ms="374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:55 IST" name="tearUp" finished-at="2024-11-13T12:19:58 IST" duration-ms="2809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method signature="loginWithInvalidEmailValidPasswordCredentials()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:58 IST" name="loginWithInvalidEmailValidPasswordCredentials" finished-at="2024-11-13T12:19:59 IST" duration-ms="854" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at comTest.Login.loginWithInvalidEmailValidPasswordCredentials(Login.java:70)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmailValidPasswordCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:59 IST" name="tearDown" finished-at="2024-11-13T12:19:59 IST" duration-ms="369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:19:59 IST" name="tearUp" finished-at="2024-11-13T12:20:03 IST" duration-ms="3950" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method signature="loginWithValidEmailInvalidPasswordCredentials()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:03 IST" name="loginWithValidEmailInvalidPasswordCredentials" finished-at="2024-11-13T12:20:05 IST" duration-ms="2014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidEmailInvalidPasswordCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:05 IST" name="tearDown" finished-at="2024-11-13T12:20:06 IST" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:06 IST" name="tearUp" finished-at="2024-11-13T12:20:09 IST" duration-ms="2870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method signature="loginWithoutProvidingCredentials()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:09 IST" name="loginWithoutProvidingCredentials" finished-at="2024-11-13T12:20:09 IST" duration-ms="952" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithoutProvidingCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:09 IST" name="tearDown" finished-at="2024-11-13T12:20:10 IST" duration-ms="226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearUp()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:10 IST" name="tearUp" finished-at="2024-11-13T12:20:13 IST" duration-ms="3053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearUp -->
        <test-method signature="loginWithValidCredentials()[pri:1, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:13 IST" name="loginWithValidCredentials" finished-at="2024-11-13T12:20:14 IST" duration-ms="768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:comTest.Login@1fa121e2]" started-at="2024-11-13T12:20:14 IST" name="tearDown" finished-at="2024-11-13T12:20:14 IST" duration-ms="296" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- comTest.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
